// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyC4JRyJksf3DT8-zib7yWh0lpFwxKz97j8',
    appId: '1:990964530406:web:9013257f7570d23deb4f27',
    messagingSenderId: '990964530406',
    projectId: 'study247-c8c0c',
    authDomain: 'study247-c8c0c.firebaseapp.com',
    storageBucket: 'study247-c8c0c.appspot.com',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAjGLxecIw-v8kff2mxZdx0r_7-ib_bbiE',
    appId: '1:990964530406:android:113ad190528a6d24eb4f27',
    messagingSenderId: '990964530406',
    projectId: 'study247-c8c0c',
    storageBucket: 'study247-c8c0c.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyCtRgdAV0CNTq6B5CDchEwz_fsgtDMs0XI',
    appId: '1:990964530406:ios:65b7754bd5213a2deb4f27',
    messagingSenderId: '990964530406',
    projectId: 'study247-c8c0c',
    storageBucket: 'study247-c8c0c.appspot.com',
    iosClientId: '990964530406-fj3kc4j86uo12iee21tpv5ub4q3qp5on.apps.googleusercontent.com',
    iosBundleId: 'com.tadyuh.study247',
  );
}
